import { Connection } from 'typeorm'
import { Factory, Seeder } from 'typeorm-seeding'
import { Item, ItemSlotType } from '../models/Item'

export default class CreateItemsSeed implements Seeder {
  public async run (factory: Factory, connection: Connection): Promise<void> {
    await connection
      .createQueryBuilder()
      .insert()
      .into(Item)
      .values([
        {
          id: 'bulb_green',
          theme: 'holiday',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'elf_suit_green',
          theme: 'holiday',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'train_hat_blue',
          theme: 'work',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'reindeer_head',
          theme: 'holiday',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'box_hat_red',
          theme: 'silly',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'bulb_yellow',
          theme: 'holiday',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'winter_dress',
          theme: 'holiday',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'elf_hat_green',
          theme: 'holiday',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'train_blue',
          theme: 'work',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'super_cape_black',
          theme: 'super',
          slot: ItemSlotType.NECK,
          cost: 100,
        },
        {
          id: 'turkey',
          theme: 'silly',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'pilgram_hat',
          theme: 'history',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'pilgram_dress',
          theme: 'history',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'bonnet_white',
          theme: 'history',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'pilgram_suit',
          theme: 'history',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'bandana_purple',
          theme: 'pirate',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'pirate_hat_hook',
          theme: 'pirate',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'wooden_barrel',
          theme: 'pirate',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'swimsuit_green',
          theme: 'summer',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'headband_blue',
          theme: 'sports',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'bb_beebee',
          theme: 'event',
          slot: ItemSlotType.HAND,
          cost: 100,
        },
        {
          id: 'ballerina_pink',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'bb_ballcap',
          theme: 'event',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'water_wings_blue',
          theme: 'sports',
          slot: ItemSlotType.HAND,
          cost: 20,
        },
        {
          id: 'bb_backpack',
          theme: 'event',
          slot: ItemSlotType.PACK,
          cost: 100,
        },
        {
          id: 'bb_astoria',
          theme: 'event',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'bb_riggs',
          theme: 'event',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'bb_oliver',
          theme: 'event',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'bb_will',
          theme: 'event',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'bb_huggable',
          theme: 'event',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'bb_headband',
          theme: 'event',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'headphones_pink',
          theme: 'theme',
          slot: ItemSlotType.EARS,
          cost: 100,
        },
        {
          id: 'skeleton_body',
          theme: 'halloween',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'skeleton_head',
          theme: 'halloween',
          slot: ItemSlotType.MASK,
          cost: 100,
        },
        {
          id: 'ghost_white',
          theme: 'halloween',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'dracula_cloak',
          theme: 'halloween',
          slot: ItemSlotType.CAPE,
          cost: 100,
        },
        {
          id: 'party_hat',
          theme: 'party',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'sun_square',
          theme: 'theme',
          slot: ItemSlotType.EYES,
          cost: 100,
        },
        {
          id: 'frank',
          theme: 'halloween',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'witch',
          theme: 'halloween',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'pumpkin',
          theme: 'halloween',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'scarf_black',
          theme: 'winter',
          slot: ItemSlotType.NECK,
          cost: 100,
        },
        {
          id: 'messenger_brown',
          theme: 'school',
          slot: ItemSlotType.BELT,
          cost: 100,
        },
        {
          id: 'ballcap_red',
          theme: 'sports',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'tinfoil_hat',
          theme: 'silly',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'school_navy_a',
          theme: 'school',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'snorkel_blue',
          theme: 'sports',
          slot: ItemSlotType.EYES,
          cost: 100,
        },
        {
          id: 'school_navy_b',
          theme: 'school',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'plaid_black',
          theme: 'adventure',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'rocket_red',
          theme: 'mascot',
          slot: ItemSlotType.PACK,
          cost: 100,
        },
        {
          id: 'overalls_orange',
          theme: 'work',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'ballcap_yellow',
          theme: 'sports',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'propeller_silver',
          theme: 'silly',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'box_brown',
          theme: 'theme',
          slot: ItemSlotType.RIDE,
          cost: 100,
        },
        {
          id: 'school_pack_orange',
          theme: 'school',
          slot: ItemSlotType.PACK,
          cost: 100,
        },
        {
          id: 'sombrero_yellow',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'hoodie_orange',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'pot_black',
          theme: 'silly',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'kit_yellow',
          theme: 'sports',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'ballcap_pink',
          theme: 'sports',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'box_hat_purple',
          theme: 'silly',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'sun_orange',
          theme: 'theme',
          slot: ItemSlotType.EYES,
          cost: 100,
        },
        {
          id: 'super_mask_black',
          theme: 'super',
          slot: ItemSlotType.MASK,
          cost: 100,
        },
        {
          id: 'hoodie_white',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'keytar_red',
          theme: 'music',
          slot: ItemSlotType.HAND,
          cost: 100,
        },
        {
          id: 'aviator_goggles_brown',
          theme: 'history',
          slot: ItemSlotType.EYES,
          cost: 100,
        },
        {
          id: 'propeller_pink',
          theme: 'silly',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'super_cape_red',
          theme: 'super',
          slot: ItemSlotType.CAPE,
          cost: 100,
        },
        {
          id: 'bandana_red',
          theme: 'pirate',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'unclesam',
          theme: 'party',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'grass_yellow',
          theme: 'hawaiian',
          slot: ItemSlotType.BELT,
          cost: 100,
        },
        {
          id: 'tshirt_black',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'lei_red',
          theme: 'hawaiian',
          slot: ItemSlotType.NECK,
          cost: 100,
        },
        {
          id: 'propeller_gold',
          theme: 'silly',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'cone',
          theme: 'silly',
          slot: ItemSlotType.NECK,
          cost: 100,
        },
        {
          id: 'box_hat_brown',
          theme: 'silly',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'propeller_blue',
          theme: 'silly',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'headphones_black',
          theme: 'gamer',
          slot: ItemSlotType.EARS,
          cost: 100,
        },
        {
          id: 'lifejacket_red',
          theme: 'sports',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'fishing_green',
          theme: 'adventure',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'guitar_blue',
          theme: 'music',
          slot: ItemSlotType.HAND,
          cost: 100,
        },
        {
          id: 'hawaii_orange',
          theme: 'hawaiian',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'goggles_black',
          theme: 'theme',
          slot: ItemSlotType.EYES,
          cost: 100,
        },
        {
          id: 'hoodie_green',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'hoodie_black',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'pickle',
          theme: 'silly',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'pirate_patch',
          theme: 'pirate',
          slot: ItemSlotType.MASK,
          cost: 100,
        },
        {
          id: 'toque_purple',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'space_blue',
          theme: 'space',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'hoodie_pink',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'float_yellow',
          theme: 'silly',
          slot: ItemSlotType.BELT,
          cost: 100,
        },
        {
          id: 'pot',
          theme: 'silly',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'monk',
          theme: 'movie',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'pirate_capt_black',
          theme: 'pirate',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'ballcap_black',
          theme: 'sports',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'ballcap_green',
          theme: 'sports',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'plaid_red',
          theme: 'adventure',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'ballcap_blue',
          theme: 'sports',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'hoodie_blue',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'bunny_white',
          theme: 'party',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'bunny_pink',
          theme: 'party',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'bunny_blue',
          theme: 'party',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'easteregg_c',
          theme: 'party',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'easteregg_b',
          theme: 'party',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'easteregg_a',
          theme: 'party',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: '3d_black',
          theme: 'movie',
          slot: ItemSlotType.EYES,
          cost: 100,
        },
        {
          id: 'tshirt_white',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'headphones_white',
          theme: 'gamer',
          slot: ItemSlotType.EARS,
          cost: 100,
        },
        {
          id: 'party_green',
          theme: 'party',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'toque_white',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'sleeping',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: '3d_white',
          theme: 'movie',
          slot: ItemSlotType.EYES,
          cost: 100,
        },
        {
          id: 'paperhat',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'space_red',
          theme: 'space',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'toque_pink',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'propeller',
          theme: 'silly',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'toque_blue',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'viking',
          theme: 'viking',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'moustache',
          theme: 'theme',
          slot: ItemSlotType.EYES,
          cost: 100,
        },
        {
          id: 'bow_white',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'clown_nose',
          theme: 'theme',
          slot: ItemSlotType.EYES,
          cost: 100,
        },
        {
          id: 'goggles_orange',
          theme: 'theme',
          slot: ItemSlotType.EYES,
          cost: 100,
        },
        {
          id: 'goggles_green',
          theme: 'theme',
          slot: ItemSlotType.EYES,
          cost: 100,
        },
        {
          id: 'goggles_blue',
          theme: 'theme',
          slot: ItemSlotType.EYES,
          cost: 100,
        },
        {
          id: 'goggles_pink',
          theme: 'theme',
          slot: ItemSlotType.EYES,
          cost: 100,
        },
        {
          id: 'watergun_yellow',
          theme: 'theme',
          slot: ItemSlotType.HAND,
          cost: 100,
        },
        {
          id: 'goggles_white',
          theme: 'theme',
          slot: ItemSlotType.EYES,
          cost: 100,
        },
        {
          id: 'angel_halo',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'bandana_black',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'bandana_yellow',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'bandana_blue',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'bandana_orange',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'bandana_pink',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'space_pack_white',
          theme: 'theme',
          slot: ItemSlotType.PACK,
          cost: 100,
        },
        {
          id: 'school_pack_blue',
          theme: 'theme',
          slot: ItemSlotType.PACK,
          cost: 100,
        },
        {
          id: 'school_pack_pink',
          theme: 'theme',
          slot: ItemSlotType.PACK,
          cost: 100,
        },
        {
          id: 'scarf_red',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'scarf_white',
          theme: 'theme',
          slot: ItemSlotType.NECK,
          cost: 100,
        },
        {
          id: 'scarf_purple',
          theme: 'theme',
          slot: ItemSlotType.NECK,
          cost: 100,
        },
        {
          id: 'scarf_pink',
          theme: 'theme',
          slot: ItemSlotType.NECK,
          cost: 100,
        },
        {
          id: 'scarf_blue',
          theme: 'theme',
          slot: ItemSlotType.NECK,
          cost: 100,
        },
        {
          id: 'propeller_black',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'tophat_gold',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'tophat_dark',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'tophat_black',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'ninja_swords',
          theme: 'theme',
          slot: ItemSlotType.PACK,
          cost: 100,
        },
        {
          id: 'grass_green',
          theme: 'theme',
          slot: ItemSlotType.BELT,
          cost: 100,
        },
        {
          id: 'backpack_green',
          theme: 'theme',
          slot: ItemSlotType.PACK,
          cost: 100,
        },
        {
          id: 'super_cape_white',
          theme: 'theme',
          slot: ItemSlotType.CAPE,
          cost: 100,
        },
        {
          id: 'super_cape_pink',
          theme: 'theme',
          slot: ItemSlotType.CAPE,
          cost: 100,
        },
        {
          id: 'super_cape_blue',
          theme: 'theme',
          slot: ItemSlotType.CAPE,
          cost: 100,
        },
        {
          id: 'jetpack',
          theme: 'theme',
          slot: ItemSlotType.PACK,
          cost: 100,
        },
        {
          id: 'santa_beard',
          theme: 'theme',
          slot: ItemSlotType.EYES,
          cost: 100,
        },
        {
          id: 'viking_pink',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'viking_blue',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'ballcap_orange',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'tshirt_orange',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'hawaii_blue',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'plaid_blue',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'plaid_pink',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'plaid_green',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'moose',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'pirate_crew_blue',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'suit_dark',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'suit_gold',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'mummy_body',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'jumpsuit_red',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'space_suit_white',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'pirate_hat_black',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'army_helmet_green',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'space_orange',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'puffy_white',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'space_black',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'puffy_red',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'puffy_pink',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'puffy_black',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'puffy_blue',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'hoodie_purple',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'gift_hat_green',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'gift_hat_red',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'pirate_capt_red',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'pirate_capt_pink',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'toque_orange',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'reindeer_body',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'santa_suit',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'ushanka',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'aviator_hat_brown',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'pirate_hat_pink',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'pirate_hat_blue',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'princess_dress_pink',
          theme: 'theme',
          slot: ItemSlotType.BELT,
          cost: 100,
        },
        {
          id: 'angel_wings',
          theme: 'theme',
          slot: ItemSlotType.BELT,
          cost: 100,
        },
        {
          id: 'santa_hat',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'roman_helmet',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'princess_hat_pink',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'wizard_blizzard',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'bb_tillman',
          theme: 'theme',
          slot: ItemSlotType.MASK,
          cost: 100,
        },
        {
          id: 'mummy_head',
          theme: 'theme',
          slot: ItemSlotType.MASK,
          cost: 100,
        },
        {
          id: 'shark_blue',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'hotdog',
          theme: 'theme',
          slot: ItemSlotType.BODY,
          cost: 100,
        },
        {
          id: 'space_helmet_white',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'fairy_wings',
          theme: 'theme',
          slot: ItemSlotType.PACK,
          cost: 100,
        },
        {
          id: 'bulb_white',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'bulb_red',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'bulb_blue',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'bulb_pink',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'candy_corn',
          theme: 'theme',
          slot: ItemSlotType.HEAD,
          cost: 100,
        },
        {
          id: 'ball_blue',
          theme: 'theme',
          slot: ItemSlotType.BELT,
          cost: 100,
        },
        {
          id: 'gelatinous_green',
          theme: 'theme',
          slot: ItemSlotType.BELT,
          cost: 100,
        },
      ])
      .execute()
  }
}
